package com.wang.eggroll.passwordbox.model.orm;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.wang.eggroll.passwordbox.model.PasswordItem;

import com.wang.eggroll.passwordbox.model.orm.PasswordItemDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig passwordItemDaoConfig;

    private final PasswordItemDao passwordItemDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        passwordItemDaoConfig = daoConfigMap.get(PasswordItemDao.class).clone();
        passwordItemDaoConfig.initIdentityScope(type);

        passwordItemDao = new PasswordItemDao(passwordItemDaoConfig, this);

        registerDao(PasswordItem.class, passwordItemDao);
    }
    
    public void clear() {
        passwordItemDaoConfig.clearIdentityScope();
    }

    public PasswordItemDao getPasswordItemDao() {
        return passwordItemDao;
    }

}
